config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    get 'profile', to: 'profile#index'

    patch 'change_access', to: 'demo#change_access'

    resources :bulletins, except: %i[destroy] do
      member do
        patch :archive, :to_moderate
      end
    end

    namespace :admin do
      root 'home#index'
      resources :bulletins do
        member do
          patch :archive, :publish, :reject
        end
      end
      resources :categories, except: %i[show]
      resources :users, only: %i[index edit update destroy]
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/controllers/web/profile_controller.rb
# frozen_string_literal: true

module Web
  class ProfileController < ApplicationController
    def index
      authenticate_user!

      @q = current_user.bulletins.ransack(params[:q])
      @bulletins = @q.result.order(updated_at: :desc).page(params[:page])
    end
  end
end

app/helpers/web/profile_helper.rb
# frozen_string_literal: true

module Web::ProfileHelper
end

app/views/web/profile/_bulletin_row.html.slim
tr
  td = bulletin.title
  td = localized_bulletin_state(bulletin.state)
  td = time_ago_in_words bulletin.created_at
  td.x-pinned-td
    .d-flex.justify-content-start.align-items-start
      div(title="#{t('web.admin.actions.show')}")
        = link_to bulletin_path(bulletin), class: 'btn btn-sm me-2' do
          i.bi.bi-eye
      div(title="#{t('web.admin.actions.edit')}")
        = link_to edit_bulletin_path(bulletin), class: 'btn btn-sm me-2' do
          i.bi.bi-pencil
      - if bulletin.may_to_moderate?
        div(title="#{t('web.admin.actions.to_moderate')}")
          = link_to to_moderate_bulletin_path(bulletin),
          data: { turbo_method: :patch }, class: 'btn btn-sm me-2' do
            i.bi.bi-rocket
      - if bulletin.may_archive?
        div(title="#{t('web.admin.actions.archive')}")
          = link_to archive_bulletin_path(bulletin),
          data: { turbo_method: :patch, turbo_confirm: t('.confirm') }, class: 'btn btn-sm' do
            i.bi.bi-archive.text-danger

app/views/web/profile/_bulletins_table.html.slim
section#bulletin-table
  .table-responsive
    table.table.table-hover.text-nowrap
      thead
        tr
          th = t('activerecord.attributes.bulletin.title')
          th = t('activerecord.attributes.bulletin.state')
          th = t('activerecord.attributes.bulletin.created_at')
          th.x-pinned-th
            = t('admin.table_headers.actions')
      tbody
        - bulletins.each do |bulletin|
          = render 'bulletin_row', bulletin:

app/views/web/profile/index.html.slim
.container.px-0.mt-4.mb-5.pb-5#profile-bulletin
  .card.shadow.p-4
    mb-4
      h2 = t('.header')
      hr
    = render 'web/shared/bulletins/search_form', url: profile_path
    = render 'bulletins_table', bulletins: @bulletins
    = render 'web/shared/pagination', pagy_object: @bulletins