config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    get 'profile', to: 'profile#index'

    patch 'change_access', to: 'demo#change_access'

    resources :bulletins, except: %i[destroy] do
      member do
        patch :archive, :to_moderate
      end
    end

    namespace :admin do
      root 'home#index'
      resources :bulletins do
        member do
          patch :archive, :publish, :reject
        end
      end
      resources :categories, except: %i[show]
      resources :users, only: %i[index edit update destroy]
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/bulletin.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bulletins
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  user_id     :integer          not null
#  category_id :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  state       :string           default("draft"), not null
#
class Bulletin < ApplicationRecord
  include AASM

  has_one_attached :image do |attached|
    attached.variant :for_form, resize_to_limit: [nil, 100]
  end

  belongs_to :user, counter_cache: :bulletins_count
  belongs_to :category

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :image,
            attached: true,
            content_type: {
              in: ['image/jpeg', 'image/jpg', 'image/png'],
              size: { less_than: 5.megabytes }
            }

  scope :latest_published, -> { where(state: :published).order(created_at: :desc) }

  def self.ransackable_attributes(_auth_object = nil)
    %w[category_id created_at description id id_value title updated_at user_id]
  end

  include AASM

  aasm column: 'state' do
    state :draft, initial: true
    state :under_moderation, :published, :rejected, :archived

    event :to_moderate do
      transitions from: %i[draft rejected], to: :under_moderation
    end

    event :publish do
      transitions from: :under_moderation, to: :published
    end

    event :reject do
      transitions from: :under_moderation, to: :rejected
    end

    event :archive do
      transitions from: %i[draft under_moderation published rejected], to: :archived
    end
  end
end

app/controllers/web/admin/bulletins_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class BulletinsController < ApplicationController
      before_action :set_bulletin,
                    only: %i[publish archive reject]

      def index
        @q = Bulletin.ransack(params[:q])
        @bulletins = @q.result.order(updated_at: :desc).page(params[:page])
      end

      def archive
        if @bulletin.may_archive?
          @bulletin.archive!
          redirect_to admin_root_path, notice: t('.success')
        else
          redirect_to admin_root_path, alert: t('.fail')
        end
      end

      def publish
        if @bulletin.may_publish?
          @bulletin.publish!
          redirect_to admin_root_path, notice: t('.success')
        else
          redirect_to admin_root_path, alert: t('.fail')
        end
      end

      def reject
        if @bulletin.may_reject?
          @bulletin.reject!
          redirect_to admin_root_path, notice: t('.success')
        else
          redirect_to admin_root_path, alert: t('.fail')
        end
      end

      private

      def set_bulletin
        @bulletin = Bulletin.find(params[:id])
      end
    end
  end
end

app/controllers/web/bulletins_controller.rb
# frozen_string_literal: true

module Web
  class BulletinsController < ApplicationController
    before_action :authenticate_user!, except: %i[index show]
    before_action :set_bulletin,
                  only: %i[show edit update archive to_moderate]

    def index
      items = signed_in? ? 11 : 12

      @q = Bulletin.published.includes(:user).with_attached_image.ransack(params[:q])
      @bulletins = @q.result.order(updated_at: :desc).page(params[:page]).per(items)
    end

    def show
      authorize @bulletin
    end

    def new
      @bulletin = current_user.bulletins.build
      authorize @bulletin
    end

    def edit
      authorize @bulletin
    end

    def create
      @bulletin = current_user.bulletins.build(bulletin_params)
      authorize @bulletin

      if @bulletin.save
        redirect_to @bulletin, notice: t('.success')
      else
        flash[:alert] = t('.fail')
        render :new, status: :unprocessable_entity
      end
    end

    def update
      authorize @bulletin

      if @bulletin.update(bulletin_params)
        redirect_to @bulletin, notice: t('.success')
      else
        flash.now['alert'] = t('.fail')
        render :edit, status: :unprocessable_entity
      end
    end

    def archive
      authorize @bulletin

      if @bulletin.may_archive?
        @bulletin.archive!
        redirect_to profile_path, notice: t('.success')
      else
        redirect_to profile_path, alert: t('.fail')
      end
    end

    def to_moderate
      authorize @bulletin

      if @bulletin.may_to_moderate?
        @bulletin.to_moderate!
        redirect_to profile_path, notice: t('.success')
      else
        redirect_to profile_path, alert: t('.fail')
      end
    end

    private

    def bulletin_params
      params.require(:bulletin).permit(:title, :description, :image, :category_id)
    end

    def set_bulletin
      @bulletin = Bulletin.find(params[:id])
    end
  end
end

app/helpers/admin/bulletins_helper.rb
# frozen_string_literal: true

module Admin::BulletinsHelper
end

app/views/admin/bulletins/_bulletin_row.html.slim
tr
  td = bulletin.title
  td = localized_bulletin_state(bulletin.state)
  td = time_ago_in_words bulletin.created_at
  td(style='position: sticky; right:  0; background: white; z-index:  1;')
    .d-flex.justify-content-start.align-items-start
      - if render_for == 'under_moderation'
        div(title="#{t('admin.actions.publish')}")
          = link_to publish_admin_bulletin_path(bulletin),
          data: { turbo_method: :patch, turbo_confirm: t('.publish.confirm') },
          class: 'btn btn-sm me-2' do
            i.bi.bi-check2-all.text-success
        div(title="#{t('admin.actions.reject')}")
          = link_to reject_admin_bulletin_path(bulletin),
          data: { turbo_method: :patch, turbo_confirm: t('.reject.confirm', action: :archive) },
          class: 'btn btn-sm me-2' do
            i.bi.bi-x-lg.text-danger-50
      - else
        div(title="#{t('admin.actions.show')}")
          = link_to bulletin_path(bulletin), class: 'btn btn-sm me-2' do
            i.bi.bi-eye
      - if bulletin.may_archive?
        div(title="#{t('admin.actions.archive')}")
          = link_to archive_admin_bulletin_path(bulletin),
          data: { turbo_method: :patch, turbo_confirm: t('.archive.confirm') },
          class: 'btn btn-sm' do
            i.bi.bi-archive.text-danger

app/views/admin/bulletins/index.html.slim
.container.px-0.mt-4.mb-5.pb-5#admin-bulletin
  .row
    .col-2
      = render 'admin/shared/nav_panel', selected: 'bulletins'
    .col
      h2.mb-4 = t('.header')
      = render 'shared/bulletins/search_form', url: admin_bulletins_url
      = render 'bulletins_table', bulletins: @bulletins, render_for: 'index'
      .div#pagination-section
        .d-flex.justify-content-center == pagy_bootstrap_nav(@pagy)

app/views/admin/bulletins/index_under_moderation.html.slim
.container.px-0.mt-4.mb-5.pb-5#admin-bulletin
  .row
    .col-2
      = render 'admin/shared/nav_panel', selected: 'under_moderation'
    .col
      h2.mb-4 = t('.header')
      = render 'bulletins_table', bulletins: @bulletins, render_for: 'under_moderation'
      .div#pagination-section
        .d-flex.justify-content-center == pagy_bootstrap_nav(@pagy)