config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    get 'profile', to: 'profile#index'

    patch 'change_access', to: 'demo#change_access'

    resources :bulletins, except: %i[destroy] do
      member do
        patch :archive, :to_moderate
      end
    end

    namespace :admin do
      root 'home#index'
      resources :bulletins do
        member do
          patch :archive, :publish, :reject
        end
      end
      resources :categories, except: %i[show]
      resources :users, only: %i[index edit update destroy]
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/bulletin.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bulletins
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  user_id     :integer          not null
#  category_id :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  state       :string           default("draft"), not null
#
class Bulletin < ApplicationRecord
  include AASM

  has_one_attached :image do |attached|
    attached.variant :for_form, resize_to_limit: [nil, 100]
  end

  belongs_to :user, counter_cache: :bulletins_count
  belongs_to :category

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :image,
            attached: true,
            content_type: {
              in: ['image/jpeg', 'image/jpg', 'image/png'],
              size: { less_than: 5.megabytes }
            }

  scope :latest_published, -> { where(state: :published).order(created_at: :desc) }

  def self.ransackable_attributes(_auth_object = nil)
    %w[category_id created_at description id id_value title updated_at user_id]
  end

  include AASM

  aasm column: 'state' do
    state :draft, initial: true
    state :under_moderation, :published, :rejected, :archived

    event :to_moderate do
      transitions from: %i[draft rejected], to: :under_moderation
    end

    event :publish do
      transitions from: :under_moderation, to: :published
    end

    event :reject do
      transitions from: :under_moderation, to: :rejected
    end

    event :archive do
      transitions from: %i[draft under_moderation published rejected], to: :archived
    end
  end
end

app/controllers/web/admin/bulletins_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class BulletinsController < ApplicationController
      before_action :set_bulletin,
                    only: %i[publish archive reject]

      def index
        @q = Bulletin.ransack(params[:q])
        @bulletins = @q.result.order(updated_at: :desc).page(params[:page])
      end

      def archive
        if @bulletin.may_archive?
          @bulletin.archive!
          redirect_to admin_root_path, notice: t('.success')
        else
          redirect_to admin_root_path, alert: t('.fail')
        end
      end

      def publish
        if @bulletin.may_publish?
          @bulletin.publish!
          redirect_to admin_root_path, notice: t('.success')
        else
          redirect_to admin_root_path, alert: t('.fail')
        end
      end

      def reject
        if @bulletin.may_reject?
          @bulletin.reject!
          redirect_to admin_root_path, notice: t('.success')
        else
          redirect_to admin_root_path, alert: t('.fail')
        end
      end

      private

      def set_bulletin
        @bulletin = Bulletin.find(params[:id])
      end
    end
  end
end

app/controllers/web/bulletins_controller.rb
# frozen_string_literal: true

module Web
  class BulletinsController < ApplicationController
    before_action :authenticate_user!, except: %i[index show]
    before_action :set_bulletin,
                  only: %i[show edit update archive to_moderate]

    def index
      items = signed_in? ? 11 : 12

      @q = Bulletin.published.includes(:user).with_attached_image.ransack(params[:q])
      @bulletins = @q.result.order(updated_at: :desc).page(params[:page]).per(items)
    end

    def show
      authorize @bulletin
    end

    def new
      @bulletin = current_user.bulletins.build
      authorize @bulletin
    end

    def edit
      authorize @bulletin
    end

    def create
      @bulletin = current_user.bulletins.build(bulletin_params)
      authorize @bulletin

      if @bulletin.save
        redirect_to @bulletin, notice: t('.success')
      else
        flash[:alert] = t('.fail')
        render :new, status: :unprocessable_entity
      end
    end

    def update
      authorize @bulletin

      if @bulletin.update(bulletin_params)
        redirect_to @bulletin, notice: t('.success')
      else
        flash.now['alert'] = t('.fail')
        render :edit, status: :unprocessable_entity
      end
    end

    def archive
      authorize @bulletin

      if @bulletin.may_archive?
        @bulletin.archive!
        redirect_to profile_path, notice: t('.success')
      else
        redirect_to profile_path, alert: t('.fail')
      end
    end

    def to_moderate
      authorize @bulletin

      if @bulletin.may_to_moderate?
        @bulletin.to_moderate!
        redirect_to profile_path, notice: t('.success')
      else
        redirect_to profile_path, alert: t('.fail')
      end
    end

    private

    def bulletin_params
      params.require(:bulletin).permit(:title, :description, :image, :category_id)
    end

    def set_bulletin
      @bulletin = Bulletin.find(params[:id])
    end
  end
end

app/helpers/admin/bulletins_helper.rb
# frozen_string_literal: true

module Admin::BulletinsHelper
end

app/views/web/bulletins/_bulletin.html.slim
.card
  img = image_tag(bulletin.image, class: 'card-img-top x-object-fit-cover')
  .card-body
    .card-title
      h4 = bulletin.title
    .card-text = simple_format(bulletin.description.truncate(100))
  .card-footer = time_ago_in_words bulletin.updated_at

app/views/web/bulletins/_form.html.slim
= simple_form_for bulletin, url: do |f|
  = f.input :title, hint: t('simple_form.hints.title_size')
  = f.input :description, hint: t('simple_form.hints.description_size')
  = f.association :category, required: true
  = f.input :image, as: :file, required: true, hint: t('simple_form.hints.image_size'),
  input_html: { direct_upload: false, class: 'form-control' }
  - if bulletin.image.attached? && bulletin.image.persisted?
    card.p-2
      = image_tag bulletin.image.variant(:for_form), class: 'img-thumbnail mb-2'
  br
  = f.button :submit, class: 'btn btn-success mt-4'

app/views/web/bulletins/_new_bulletin.html.slim
= link_to new_bulletin_path do
  .card.h-100.x-minimal-card-size
    .card-body.position-absolute.top-50.start-50.translate-middle
      i.bi.bi-plus-square.fs-1

app/views/web/bulletins/edit.html.slim
.container.px-0.mt-4.mb-5.pb-5
  .card.p-4.shadow
    mb-4
      h2 = t('.header')
      hr
    = render 'form', bulletin: @bulletin, url: bulletin_path(@bulletin)

app/views/web/bulletins/index.html.slim
.container.px-0.mt-4.mb-5.pb-5
  .card.p-4.shadow
    mb-4
      h2 = t('.header')
      hr
    .row#bulletin-search-form
      = render 'web/shared/bulletins/search_form', url: root_url
    .row.mt-4#bulletins-section
      - if signed_in?
        .col-lg-3.col-md-4.col-sm-6.mb-4
          = render 'new_bulletin'
      - @bulletins.latest_published.each do |bulletin|
        .col-lg-3.col-md-4.col-sm-6.mb-4
          = link_to bulletin_path(bulletin), class: 'text-decoration-none' do
            = render 'bulletin', bulletin:
    = render 'web/shared/pagination', pagy_object: @bulletins

app/views/web/bulletins/new.html.slim
.container.px-0.mt-4.mb-5.pb-5
  .card.p-4.shadow
    mb-4
      h2 = t('.header')
      hr
    = render 'form', bulletin: @bulletin, url: bulletins_path

app/views/web/bulletins/show.html.slim
.container.px-0.mt-4.mb-5.pb-5
  .card.shadow.p-4
    .row.mt-4
      .col
        section#bulletin-info
        .row
          - if policy(@bulletin).edit?
            .col-1
              div(title="#{t('web.admin.actions.edit')}")
                = link_to edit_bulletin_path(@bulletin), class: 'btn btn-sm me-2' do
                  i.bi.bi-pencil
          .col-auto
            h4 = @bulletin.title
        .row
          small.text-muted = @bulletin.user.name
          p = simple_format(@bulletin.description)
      .col
        section#bulletin-cover
          .col.p-2.shadow
            = image_tag(@bulletin.image, class: 'img-fluid')