config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    get 'profile', to: 'profile#index'

    patch 'change_access', to: 'demo#change_access'

    resources :bulletins, except: %i[destroy] do
      member do
        patch :archive, :to_moderate
      end
    end

    namespace :admin do
      root 'home#index'
      resources :bulletins do
        member do
          patch :archive, :publish, :reject
        end
      end
      resources :categories, except: %i[show]
      resources :users, only: %i[index edit update destroy]
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  admin           :boolean
#  bulletins_count :integer          default(0)
#
class User < ApplicationRecord
  has_many :bulletins, dependent: :destroy

  validates :email, presence: true, uniqueness: true
end

app/controllers/web/admin/users_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class UsersController < ApplicationController
      before_action :set_user, only: %i[show edit update destroy]

      def index
        @users = User.order(:id).page(params[:page])
      end

      def show; end

      def edit; end

      def update
        if @user.update(user_params)
          redirect_to admin_users_path, notice: t('.success')
        else
          flash[:alert] = t('.fail')
          render :edit, status: :unprocessable_entity
        end
      end

      def destroy
        if @user.destroy
          redirect_to admin_users_path, notice: t('.success')
        else
          flash[:alert] = t('.fail')
          render :edit, status: :unprocessable_entity
        end
      end

      private

      def user_params
        params.require(:user).permit(:name, :email, :admin)
      end

      def set_user
        @user = User.find(params[:id])
      end
    end
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/views/web/admin/users/_form.html.slim
= simple_form_for @user, url: do |f|
  = f.input :name
  = f.input :email, input_html: { class: 'form-control disabled', disabled: true }
  = f.input :admin, as: :boolean
  = f.button :submit, class: 'btn btn-primary'
  = link_to t('web.admin.actions.back'), admin_users_path, class: 'btn mx-2'

app/views/web/admin/users/_user_row.html.slim
tr
  td = user.id
  td = user.name
  td = user.email
  td = user.bulletins_count
  td
    - if user.admin?
      i.bi.bi-circle-fill.text-success
    - else
      i.bi.bi-circle-fill.text-danger
  td.x-pinned-td
    .d-flex.justify-content-start.align-items-end
      div(title="#{t('web.admin.actions.edit')}")
        = link_to edit_admin_user_path(user), class: 'btn btn-sm me-2' do
          i.bi.bi-pencil
      div(title="#{t('web.admin.actions.delete')}")
        = link_to admin_user_path(user),
        data: { turbo_method: :delete, turbo_confirm: t('.confirm') },
        class: 'btn btn-sm' do
          i.bi.bi-trash.text-danger

app/views/web/admin/users/_users_table.html.slim
table.table
  thead
    tr
      th = t('activerecord.attributes.user.id')
      th = t('activerecord.attributes.user.name')
      th = t('activerecord.attributes.user.email')
      th = t('activerecord.attributes.user.bulletins')
      th = t('activerecord.attributes.user.admin')
      th.x-pinned-th
        = t('admin.table_headers.actions')
  tbody
    - @users.each do |user|
      = render 'user_row', user:

app/views/web/admin/users/edit.html.slim
.container.px-0.mt-4.mb-5.pb-5#admin-bulletin
  .row
    .col-2
      = render 'web/admin/shared/nav_panel', selected: 'users'
    .col
      h2.mb-4 = t('.header')
      = render 'form', url: admin_user_path(@user)

app/views/web/admin/users/index.html.slim
.container.px-0.mt-4.mb-5.pb-5#admin-users
  .row
    .col-2
      = render 'web/admin/shared/nav_panel', selected: 'users'
    .col
      h2.mb-4 = t('.header')
      = render 'users_table', users: @users
      = render 'web/shared/pagination', pagy_object: @users